const STORAGE_KEY="mx-suspension-tool-v1-static";
const DEFAULT_BIKES=["KX250F","KX85","KTM 65 SX","SX-F 250"];
const INITIAL_FORM={bike:"KX250F",bikeCustom:"",track:"",surface:"mixed",weather:"damp",forkCompression:12,forkRebound:12,shockHigh:"1.5",shockLow:12,shockRebound:12,sag:105,notes:""};
const SYMPTOM_GUIDE={neutral:{label:"Kein Symptom ausgewählt",tips:["Das Diagramm bewertet X und Y getrennt.","Nimm das aktuelle Setup als Basis.","Später können hier fahrzeugspezifische Regeln ergänzt werden."]},turn_in:{label:"Lenkt schlecht ein",tips:["Gabel leicht durchschieben.","Vorn etwas weicher oder hinten weniger Sag prüfen.","Reifendruck und Reifenbild mitdenken."]},front_sand_push:{label:"Vorderrad rutscht im Sand weg",tips:["Setup etwas Richtung Hartboden verschieben.","Die Gabel nicht unnötig weich abstimmen.","Fahrerposition und Last auf dem Vorderrad prüfen."]},rear_kick:{label:"Heck kickt über Kanten",tips:["Shock-Rebound prüfen.","High-Speed hinten nicht zu straff fahren.","Sag kontrollieren."]},harsh_front:{label:"Vorne hart oder unruhig",tips:["Gabel-Compression etwas öffnen.","Rebound mit anschauen.","Servicezustand prüfen."]},lazy_rear:{label:"Heck schwammig oder träge",tips:["Weniger Sag oder mehr Low-Speed testen.","Zu weiche Basis hinten vermeiden.","Nur kleine Schritte ändern."]}};
const state={bikes:[...DEFAULT_BIKES],setups:[],bikeDrafts:{},form:{...INITIAL_FORM},selectedSymptom:"neutral",selectedTrack:"__all__"};
const $=id=>document.getElementById(id);
const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number(v)||0));
const clampFloat=(v,min,max)=>Math.min(max,Math.max(min,Number(v)||0));
const getHighspeedNumeric=v=>v==="n.v."?1.5:clampFloat(v,.5,3);
const createBikeDraft=bike=>({...INITIAL_FORM,bike,bikeCustom:bike==="__custom__"?"":""});
const mapWeather=s=>s<=24?"Nass":s<=42?"Feucht":s<=60?"Neutral":s<=78?"Trocken":"Sehr trocken";
const mapSurface=s=>s<=22?"Hartboden":s<=40?"Hart/Misch":s<=60?"Mischboden":s<=78?"Lehmig":"Sand";
function analysis(form){const fc=form.forkCompression/22,fr=form.forkRebound/22,sl=form.shockLow/22,sr=form.shockRebound/22,sh=(getHighspeedNumeric(form.shockHigh)-.5)/2.5,sag=(clamp(form.sag,90,120)-90)/30;const ff=fc*.55+fr*.25+(1-sag)*.2,rf=sl*.45+sh*.3+sr*.15+(1-sag)*.1,firm=ff*.52+rf*.48;const hold=(1-sag)*.45+sh*.2+sl*.15+fr*.1+sr*.1,plush=sag*.4+(1-sh)*.2+(1-sl)*.2+(1-fc)*.2;const corner=fc*.3+fr*.18+(1-sag)*.22+(1-sh)*.08+(1-sl)*.1+(1-sr)*.12,stab=sh*.22+sl*.22+sr*.18+sag*.18+fc*.1+fr*.1;const x=clamp(Math.round(50+(stab-corner)*55+(firm-.5)*18),10,90),y=clamp(Math.round(50+(hold-plush)*55),10,90);const reasons=[];if(fc>=.68)reasons.push("straffe Gabel-Compression");if(sl>=.68)reasons.push("straffes Low-Speed hinten");if(sh>=.6)reasons.push("viel High-Speed-Dämpfung");if(sag<=.35)reasons.push("wenig Sag / mehr Hold-up");if(fc<=.36)reasons.push("weiche Gabel-Compression");if(sl<=.36)reasons.push("weiches Low-Speed hinten");return{x,y,surfaceLabel:mapSurface(x),weatherLabel:mapWeather(y),confidence:Math.round(58+Math.abs(firm-.5)*45+Math.abs(hold-plush)*15),reasons:reasons.slice(0,5),firmness:Math.round(firm*100),holdUp:Math.round(hold*100),frontBias:Math.round(ff*100),rearBias:Math.round(rf*100)}}
const resolvedBike=()=>state.form.bike==="__custom__"?state.form.bikeCustom.trim():state.form.bike;
const bikeKey=()=>state.form.bike==="__custom__"?(state.form.bikeCustom.trim()?`custom:${state.form.bikeCustom.trim()}`:"__custom__"):state.form.bike;
const setupLabel=(s,w)=>`${s} · ${w}`;
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify({bikes:state.bikes,setups:state.setups,bikeDrafts:state.bikeDrafts}))}
function load(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;try{const d=JSON.parse(raw);if(Array.isArray(d.bikes))state.bikes=d.bikes;if(Array.isArray(d.setups))state.setups=d.setups;if(d.bikeDrafts&&typeof d.bikeDrafts==="object")state.bikeDrafts=d.bikeDrafts}catch(e){console.warn(e)}}
function syncDraft(){state.bikeDrafts[bikeKey()]={...state.form};persist()}
function bikeSetups(){const bike=resolvedBike();return bike?state.setups.filter(s=>s.bike===bike):[]}
function bikeTracks(){const m=new Map();bikeSetups().forEach(e=>{const k=e.track?.trim()||"Ohne Strecke";if(!m.has(k))m.set(k,{name:k,count:0,latest:e.createdAt});const c=m.get(k);c.count+=1;if(new Date(e.createdAt)>new Date(c.latest))c.latest=e.createdAt});return[...m.values()].sort((a,b)=>new Date(b.latest)-new Date(a.latest))}
function visibleSetups(){return state.selectedTrack==="__all__"?bikeSetups():bikeSetups().filter(e=>(e.track?.trim()||"Ohne Strecke")===state.selectedTrack)}
function switchBike(name){state.selectedTrack="__all__";state.form=state.bikeDrafts[name]?{...state.bikeDrafts[name]}:createBikeDraft(name);render()}
function addBike(){const name=$("newBikeInput").value.trim();if(!name)return;if(state.bikes.includes(name)){switchBike(name);$("newBikeInput").value="";return}state.bikes.push(name);state.bikeDrafts[name]=createBikeDraft(name);state.form=createBikeDraft(name);state.selectedTrack="__all__";$("newBikeInput").value="";persist();render()}
function deleteBike(){const bike=resolvedBike();if(!bike||state.form.bike==="__custom__")return;if(!confirm(`Motorrad "${bike}" inklusive Setups löschen?`))return;state.bikes=state.bikes.filter(b=>b!==bike);state.setups=state.setups.filter(s=>s.bike!==bike);delete state.bikeDrafts[bike];state.form=state.bikes.length?(state.bikeDrafts[state.bikes[0]]||createBikeDraft(state.bikes[0])):createBikeDraft("__custom__");state.selectedTrack="__all__";persist();render()}
function saveSetup(){const bike=resolvedBike();if(!bike)return;const a=analysis(state.form);const entry={id:crypto.randomUUID(),createdAt:new Date().toISOString(),bike,track:state.form.track.trim(),surface:state.form.surface,weather:state.form.weather,forkCompression:state.form.forkCompression,forkRebound:state.form.forkRebound,shockHigh:state.form.shockHigh,shockLow:state.form.shockLow,shockRebound:state.form.shockRebound,sag:state.form.sag,notes:state.form.notes.trim(),derivedSurface:a.surfaceLabel,derivedWeather:a.weatherLabel,derivedX:a.x,derivedY:a.y};state.setups.unshift(entry);state.selectedTrack=entry.track||"Ohne Strecke";persist();render()}
function loadSetup(entry){state.form={bike:state.bikes.includes(entry.bike)?entry.bike:"__custom__",bikeCustom:state.bikes.includes(entry.bike)?"":entry.bike,track:entry.track||"",surface:entry.surface||"mixed",weather:entry.weather||"damp",forkCompression:entry.forkCompression,forkRebound:entry.forkRebound,shockHigh:entry.shockHigh,shockLow:entry.shockLow,shockRebound:entry.shockRebound,sag:entry.sag,notes:entry.notes||""};state.selectedTrack=entry.track?.trim()||"Ohne Strecke";syncDraft();render()}
function deleteSetup(id){state.setups=state.setups.filter(s=>s.id!==id);persist();render()}
function slider(label,key){const v=state.form[key];return `<div class="slider-box"><div class="slider-head"><label>${label}</label><div class="inline-row"><input class="text-input number-input" type="number" min="0" max="22" value="${v}" data-key="${key}" data-role="number"><span class="small subtle">Clicks</span></div></div><input class="range" type="range" min="0" max="22" step="1" value="${v}" data-key="${key}" data-role="range"><div class="slider-values"><span>0</span><span>${v}</span><span>22</span></div></div>`}
function renderBikeDashboard(){const wrap=$("bikeDashboard");wrap.innerHTML="";state.bikes.forEach(b=>{const active=state.form.bike===b;const el=document.createElement("button");el.className=`bike-card ${active?"active":""}`;el.innerHTML=`<div class="eyebrow">Motorrad</div><div class="bike-card-title">${b}</div><div class="subtle small">Setup laden und bearbeiten</div>`;el.onclick=()=>switchBike(b);wrap.appendChild(el)});const c=document.createElement("button");c.className=`bike-card ${state.form.bike==="__custom__"?"active":""}`;c.innerHTML=`<div class="eyebrow">Motorrad</div><div class="bike-card-title">Eigenes Bike</div><div class="subtle small">Neues Motorrad anlegen</div>`;c.onclick=()=>switchBike("__custom__");wrap.appendChild(c)}
function bindInputs(){["bikeCustom","track","surface","weather","shockHigh","notes"].forEach(id=>{const el=$(id);if(!el)return;el.oninput=el.onchange=e=>{state.form[id]=e.target.value;syncDraft();render()}});const sag=$("sag");sag.oninput=sag.onchange=e=>{state.form.sag=clamp(e.target.value,80,130);syncDraft();render()};document.querySelectorAll('[data-role="number"],[data-role="range"]').forEach(el=>{el.oninput=e=>{const key=e.target.dataset.key;state.form[key]=clamp(e.target.value,0,22);syncDraft();render()}})}
function renderForm(){const bike=resolvedBike();$("activeBikeChip").textContent=bike||"Kein Motorrad";$("currentBikeLabel").textContent=bike||"-";$("editorTitle").textContent=`Basisdaten – ${bike||'ohne Bike'}`;$("deleteBikeBtn").style.display=state.form.bike==="__custom__"?"none":"";$("customBikeField").hidden=state.form.bike!=="__custom__";$("bikeCustom").value=state.form.bikeCustom;$("track").value=state.form.track;$("surface").value=state.form.surface;$("weather").value=state.form.weather;$("shockHigh").value=state.form.shockHigh;$("sag").value=state.form.sag;$("notes").value=state.form.notes;$("forkCompressionWrap").innerHTML=slider("Compression","forkCompression");$("forkReboundWrap").innerHTML=slider("Rebound","forkRebound");$("shockLowWrap").innerHTML=slider("Lowspeed Compression","shockLow");$("shockReboundWrap").innerHTML=slider("Rebound","shockRebound");bindInputs()}
function renderAnalysis(){const a=analysis(state.form);$("surfaceChip").textContent=a.surfaceLabel;$("weatherChip").textContent=a.weatherLabel;$("confidenceChip").textContent=`Treffer ${a.confidence}%`;$("analysisSurface").textContent=a.surfaceLabel;$("analysisWeather").textContent=a.weatherLabel;$("analysisFirmness").textContent=`${a.firmness}%`;$("analysisHoldUp").textContent=`${a.holdUp}%`;$("analysisFront").textContent=`${a.frontBias}%`;$("analysisRear").textContent=`${a.rearBias}%`;const p=$("terrainPoint");p.style.left=`${a.x}%`;p.style.top=`${a.y}%`;const r=$("reasonList");r.innerHTML="";(a.reasons.length?a.reasons:["Aktuell eher neutrales Basis-Setup."]).forEach(t=>{const el=document.createElement("div");el.className="reason-pill";el.textContent=t;r.appendChild(el)})}
function renderTracks(){const filter=$("trackFilterRow"),list=$("trackList");filter.innerHTML="";list.innerHTML="";const all=document.createElement("button");all.className=`btn ${state.selectedTrack==="__all__"?"primary":""}`;all.textContent="Alle Strecken";all.onclick=()=>{state.selectedTrack="__all__";render()};filter.appendChild(all);const tracks=bikeTracks();if(!tracks.length){list.innerHTML='<div class="empty-state">Für dieses Bike gibt es noch keine gespeicherten Strecken-Setups.</div>';return}tracks.forEach(t=>{const chip=document.createElement("button");chip.className=`btn ${state.selectedTrack===t.name?"primary":""}`;chip.textContent=`${t.name} (${t.count})`;chip.onclick=()=>{state.selectedTrack=t.name;render()};filter.appendChild(chip);const item=document.createElement("button");item.className=`track-item ${state.selectedTrack===t.name?"active":""}`;item.innerHTML=`<div class="setup-item-head"><div><strong>${t.name}</strong><div class="setup-meta">${t.count} gespeicherte Setups</div></div><div class="setup-meta">${new Date(t.latest).toLocaleDateString('de-DE')}</div></div>`;item.onclick=()=>{state.selectedTrack=t.name;render()};list.appendChild(item)})}
function renderTips(){const select=$("selectedSymptom");if(!select.options.length){Object.entries(SYMPTOM_GUIDE).forEach(([k,v])=>{const o=document.createElement("option");o.value=k;o.textContent=v.label;select.appendChild(o)})}select.value=state.selectedSymptom;select.onchange=e=>{state.selectedSymptom=e.target.value;renderTips()};const list=$("tipList");list.innerHTML="";SYMPTOM_GUIDE[state.selectedSymptom].tips.forEach(t=>{const el=document.createElement("div");el.className="tip-item";el.textContent=t;list.appendChild(el)})}
function renderSetups(){const list=$("setupList");list.innerHTML="";const entries=visibleSetups();if(!entries.length){list.innerHTML=`<div class="empty-state">Für dieses Bike${state.selectedTrack!=="__all__"?` auf der Strecke ${state.selectedTrack}`:""} sind noch keine Setups gespeichert.</div>`;return}entries.forEach(e=>{const el=document.createElement("div");el.className="setup-item";el.innerHTML=`<div class="setup-item-head"><div><strong>${e.bike}</strong><div class="setup-meta">${e.track||'Ohne Strecke'} · ${setupLabel(e.derivedSurface||'—',e.derivedWeather||'—')}</div></div><div class="setup-meta">${new Date(e.createdAt).toLocaleDateString('de-DE')}</div></div><div class="setup-grid"><div>Fork Comp.: <strong>${e.forkCompression}</strong></div><div>Fork Reb.: <strong>${e.forkRebound}</strong></div><div>Shock High: <strong>${e.shockHigh}</strong></div><div>Shock Low: <strong>${e.shockLow}</strong></div><div>Shock Reb.: <strong>${e.shockRebound}</strong></div><div>Sag: <strong>${e.sag} mm</strong></div></div>${e.notes?`<div class="setup-meta" style="margin-top:10px;">${e.notes}</div>`:''}<div class="setup-actions"><button class="btn">Laden</button><button class="btn danger">Löschen</button></div>`;const [loadBtn,delBtn]=el.querySelectorAll("button");loadBtn.onclick=()=>loadSetup(e);delBtn.onclick=()=>deleteSetup(e.id);list.appendChild(el)})}
function render(){renderBikeDashboard();renderForm();renderAnalysis();renderTracks();renderTips();renderSetups();persist()}
function bindActions(){$("addBikeBtn").onclick=addBike;$("deleteBikeBtn").onclick=deleteBike;$("saveSetupBtn").onclick=saveSetup;$("resetFormBtn").onclick=()=>{state.form=createBikeDraft(state.form.bike);syncDraft();render()}}
function tests(){console.assert(clamp(30,0,22)===22,'clamp upper failed');console.assert(clamp(-5,0,22)===0,'clamp lower failed');console.assert(getHighspeedNumeric('n.v.')===1.5,'highspeed n.v. failed');const a=analysis(INITIAL_FORM);console.assert(a.x>=10&&a.x<=90,'analysis x range failed');console.assert(a.y>=10&&a.y<=90,'analysis y range failed')}
load();bindActions();tests();render();
